package test

import (
	"errors"
	"testing"

	"atalariq/menu-api/internal/model"
	"atalariq/menu-api/internal/service"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

type MockRepository struct {
	mock.Mock
}

type MockAIService struct {
	mock.Mock
}

func (m *MockAIService) GenerateDescription(name string, ingredients []string) (string, error) {
	args := m.Called(name, ingredients)
	return args.String(0), args.Error(1)
}

func (m *MockAIService) GetRecommendations(request model.RecommendationRequest, menus []model.Menu) ([]model.RecommendationResponseRaw, error) {
	args := m.Called(request, menus)
	return args.Get(0).([]model.RecommendationResponseRaw), args.Error(1)
}

func (m *MockRepository) Create(menu *model.Menu) error {
	args := m.Called(menu)
	return args.Error(0)
}

func (m *MockRepository) FindAll(filter model.MenuFilter) ([]model.Menu, model.PaginationResponse, error) {
	return nil, model.PaginationResponse{}, nil
}

func (m *MockRepository) FindByID(id uint) (model.Menu, error)        { return model.Menu{}, nil }
func (m *MockRepository) Update(menu *model.Menu) error               { return nil }
func (m *MockRepository) Delete(id uint) error                        { return nil }
func (m *MockRepository) GroupBy(mode string, limit int) (any, error) { return nil, nil }

func TestCreateMenu_Success(t *testing.T) {
	mockRepo := new(MockRepository)
	mockAI := new(MockAIService)

	svc := service.NewMenuService(mockRepo, mockAI)

	// Data Input
	input := model.Menu{
		Name:        "Burger",
		Price:       50000,
		Ingredients: []string{"bun", "meat"},
	}

	mockAI.On("GenerateDescription", "Burger", []string{"bun", "meat"}).
		Return("Tasty Burger generated by Mock", nil)

	expectedDataSaved := input
	expectedDataSaved.Description = "Tasty Burger generated by Mock"

	mockRepo.On("Create", &expectedDataSaved).Return(nil)

	result, err := svc.Create(input)

	assert.NoError(t, err)
	assert.Equal(t, "Tasty Burger generated by Mock", result.Description)

	mockAI.AssertExpectations(t)
	mockRepo.AssertExpectations(t)
}

func TestCreateMenu_AIFailure_Fallback(t *testing.T) {
	mockRepo := new(MockRepository)
	mockAI := new(MockAIService)
	svc := service.NewMenuService(mockRepo, mockAI)

	input := model.Menu{Name: "Burger", Price: 50000}

	mockAI.On("GenerateDescription", mock.Anything, mock.Anything).
		Return("", errors.New("gemini quota exceeded"))

	expectedFallback := input
	expectedFallback.Description = "Delicious Burger"

	mockRepo.On("Create", &expectedFallback).Return(nil)

	svc.Create(input)

	mockRepo.AssertExpectations(t)
}
